### ISSUE TITLE
Add support for Docker Machine

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#148]

**Comment by arun-gupta** [comment]
This need to be completed by Aug 25, so that it can be incorporated in docker-java lab.

**Comment by lordofthejars** [comment]
Probably it will be possible because docker-compose support is almost finished and I will start with this issue.

**Comment by arun-gupta** [comment]
Is there an issue for docker-compose?

**Comment by lordofthejars** [comment]
No, it is implemented but need to write some tests. In fact it is support for docker-compose format, not docker-compose tool. So basically you can describe like you are doing with cube format but using docker-compose format. So developers that use docker-compose can write docker-compose files and reuse them for Cube.

**Comment by arun-gupta** [comment]
Examples?

**Comment by lordofthejars** [comment]
For example in Java EE samples Cube example you are using in arquillian.xml next format:

```
wildfly:
  buildImage:
    dockerfileLocation: src/test/resources/wildfly
    noCache: true
    remove: true
  exposedPorts: [8080/tcp, 9990/tcp]
  await:
    strategy: polling
  portBindings: [8081->8080/tcp, 9991->9990/tcp]
```

When we release docker compose format support you will be able to use it for describing your scenario. In case of previous example would be be something like:

```
wildfly:
  build: src/test/resources/wildfly
  ports: 
    - "8080:8080"
    - "9991:9990"
```

Notice that you will be able to create an external docker compose file. Then you can run docker-compose script passing that file (for example because you want to do some kind of manual testing or manual deploying) and the same file it can be used for your automatic tests.
