### ISSUE TITLE
Support extension of Docker Image configuration

### ISSUE THREAD

**Issue by aslakknutsen** [arquillian/arquillian-cube#32]
When defining multiple similar Docker containers it would be useful to allow some form of extensions model where you can override only the few parameters that change.

e.g. 

``` yaml
    wildfly:
      buildImage:
        dockerfileLocation: src/test/resources/wildfly
        noCache: true
        remove: true
      exposedPorts: [8080/tcp, 9990/tcp]
      await:
        strategy: polling
      links:
        - database:database             
      portBindings:
        - exposedPort: 8080/tcp
          port: 8081
        - exposedPort: 9990/tcp
          port: 9991
    wildfly2:
      extends: wildfly
      portBindings:
        - exposedPort: 8080/tcp
          port: 8082
        - exposedPort: 9990/tcp
          port: 9992
```
