### ISSUE TITLE
Change port binding configuration parameters

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#42]
Currently port binding is configured by using a list of objects in yaml. 

```
portBindings:
          - exposedPort: 8089/tcp
            port: 8089

          - exposedPort: 8080/tcp
            port: 8080
```

To avoid user having to write many lines with redundant information, this will be changed to:

```
portBindings: [8080:8080/tcp, 8089:8089/tcp]
```
