### ISSUE TITLE
Couldn't create a service with mentioned networks in docker-compose.yml version 2

### ISSUE THREAD

**Issue by dipak-pawar** [arquillian/arquillian-cube#470]
docker-compose - 
```yml
version: '2'
services:
  pingpong:
    image: jonmorehouse/ping-pong
    ports:
        - "8080:8080"
    networks:
        - front-tier

networks:
  front-tier:
```

network inspect logs https://gist.github.com/dipak-pawar/b57c28ee999b02f7f438ec0198e28eac

It's creating container with default NetworkMode as `default` & networks as `bridge`
It should create a container with network mentioned in docker-compose.yml & start container.
