### ISSUE TITLE
Add support for network ipam

### ISSUE THREAD

**Issue by lordofthejars** [arquillian/arquillian-cube#484]
Currently networking is support without IPAM options. An example of docker compose with ipam might be:

```
version: '2'

services:
  app:
    image: busybox
    command: ifconfig
    networks:
      app_net:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10

networks:
  app_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
      - subnet: 172.16.238.0/24
        gateway: 172.16.238.1
      - subnet: 2001:3984:3989::/64
        gateway: 2001:3984:3989::1
```

This issue implies adding support for `driver_ops` (if supported by docker-java), and the ipam elements in networks section.
1. This implies modifying the custom cube format for adding support for IPAM, it is partially supported https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/client/config/Network.java#L8 but `driver_opts` not added yet
2. Adding the logic in DockerClientExecutor https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/DockerClientExecutor.java#L889 
3. Add in DockerComposeConverter the logic to convert from DockerCompose to Cube format https://github.com/arquillian/arquillian-cube/blob/master/docker/docker/src/main/java/org/arquillian/cube/docker/impl/docker/compose/ComposeBuilder.java#L66

Finally `ipv4_address` and `ipv6_address` fields of container network section must be set (and this is something to explore how to do it since it is not clear how to do it with docker-java)
