### ISSUE TITLE
Arquillian cube should wait for all the containers to be up and running

### ISSUE THREAD

**Issue by vinsguru** [arquillian/arquillian-cube#680]
Unable to use Arquillian Graphene page objects with Arquillian Cube. Even before containers are ready, Arquillian Graphene/drone tries inject the page objects.

---------------

My cube compose file is as shown below.

```
selenium-hub:
  image: selenium/hub
  container_name: selenium-hub
  ports:
    - "4444:4444"
chrome:
  image: selenium/node-chrome
  links:
    - selenium-hub:hub
firefox:
  image: selenium/node-firefox
  links:
    - selenium-hub:hub
```
Arquillian.xml config for docker and drone.

```
 <extension qualifier="docker">
  <property name="serverVersion">1.27</property>
  <property name="serverUri">tcp://10.11.12.13:2375</property>
  <property name="dockerContainersFile">docker-compose.yml</property>
</extension>
 
 <extension qualifier="webdriver">
      <property name="remoteAddress">http://10.11.12.13:4444/wd/hub</property>
      <property name="browser">chrome</property> 
      <property name="remote">true</property>
      <property name="remoteReusable">true</property>
 </extension>
```
TestNG test using selenium grid.
```
	@Page
        Google google;

       @Test
	public void canGoogleSuggest(){
		google.getSearchWidget().searchFor("Arquillian");
		google.getSuggestions().show();
		Assert.assertEquals(google.getSuggestions().getCount(), 4);	
	}
```
I get the exception as grid does to seem to have been yet ready!!

> org.openqa.selenium.WebDriverException: Error forwarding the new session Empty pool of VM for setup Capabilities

If I add some wait, it works fine.

	@Test
	public void canGoogleSuggest(){
                Thread.sleep(1000);
		Google google = Graphene.goTo(Google.class);
		google.getSearchWidget().searchFor("Arquillian");
		google.getSuggestions().show();
		Assert.assertEquals(google.getSuggestions().getCount(), 4);	
	}
