### ISSUE TITLE
 java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#726]
```
docker version:
Version:      17.05.0-ce
```

Arquillian dependencies:
```
    compile group: 'org.jboss.arquillian.junit', name: 'arquillian-junit-standalone', version: '1.1.13.Final'
    compile group: 'org.arquillian.cube', name: 'arquillian-cube-docker', version: '1.5.0'
    compile group: 'org.arquillian.cube', name: 'arquillian-cube-api', version: '1.5.0'
    compile group: 'org.arquillian.cube', name: 'arquillian-cube-spi', version: '1.5.0'
    compile group: 'org.arquillian.cube', name: 'arquillian-cube-core', version: '1.5.0'
    compile group: 'org.jboss.arquillian.extension', name: 'arquillian-phantom-driver', version: '1.2.1.1'
    compile group: 'org.jboss.arquillian.container', name: 'arquillian-container-test-spi', version: '1.1.13.Final'
```
docker-compose yml file:

```
`version: '2.2'
services:
  ui:
    image: 'ui:latest'
    publishAllPorts: true
    attachStdin: true
    dnsSearch: [localhost]
    alwaysPull: true
    ports: [4200->80/tcp]
  datamock:
    image: 'mock:latest'
    attachStdin: true
    networkMode: host
    privileged: true
    alwaysPull: true
    dnsSearch: [losthost]
    env:
      - server.port=5555
    ports: [5555->5555/tcp]
    restartPolicy:
          name: failure
          maximumRetryCount: 2
  engine:
    image: 'engine:latest'
    publishAllPorts: true
    attachStdin: true
    alwaysPull: true
    dnsSearch: [localhost]
    env: [server.port=6666]
    ports: [8081->6666/tcp]
    restartPolicy:
          name: failure
          maximumRetryCount: 2
  database:
    image: 'cassandra:latest'
    publishAllPorts: true
    attachStdin: true
    alwaysPull: false
    dnsSearch: [localhost]
    cpuShares: 5
    cpuQuota: 5000
    ports: [9042->9042/tcp,8943->8943/tcp]
    restartPolicy:
          name: failure
          maximumRetryCount: 2
  service:
    image: 'config:latest'
    publishAllPorts: true
    attachStdin: true
    alwaysPull: false
    dnsSearch: [localhost]
    ports: [8080->8080/tcp]
    links:
       - database
    dependsOn: database
    env:
        - cassandra.contactpoints=database
    restartPolicy:
        name: failure
        maximumRetryCount: 2
    manual: true`
```

Arquillian.xml

`<?xml version="1.0"?>
<arquillian xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://jboss.org/schema/arquillian"
            xsi:schemaLocation="http://jboss.org/schema/arquillian
  http://jboss.org/schema/arquillian/arquillian_1_0.xsd">

    <extension qualifier="cube">
        <property name="connectionMode">STARTANDSTOP</property>
    </extension>

    <extension qualifier="docker">
        
        <property name="serverUri">http://localhost:2375</property>
        <property name="clean">true</property>
        <property name="dockerContainersFile">src/test/resources/docker-compose.yml</property>
        <property name="definitionFormat">COMPOSE</property>
        <property name="cleanBuildImage">true</property>
        <property name="autoStartContainers">custom:setup.AutoStartContainersOrder</property>
        <property name="cubeSpecificProperties">
            database:
                await:
                    strategy: log
                    match: 'DSE startup complete'
                    sleepPollingTime: 10 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
            ui:
                await:
                    strategy: polling
                    sleepPollingTime: 10 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
            service:
                await:
                    strategy: polling
                    sleepPollingTime: 10 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
            datamock:
                await:
                    strategy: log
                    match: 'Successfully connected'
                    sleepPollingTime: 10 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
            engine:
                await:
                    strategy: log
                    match: 'Message broker is not set up'
                    sleepPollingTime: 5 s
                    iterations: 5
                    stdOut: true
                    stdErr: true
                    timeout: 1800
        </property>
    </extension>
</arquillian>`

Code Erroring out:
DockerComposeConverter.java

`public DockerCompositions convert() {
        DockerCompositions dockerCompositions = new DockerCompositions();

        Set<String> names = dockerComposeDefinitionMap.keySet();

        boolean isV2 = names.contains(DOCKER_COMPOSE_VERSION_KEY) && DOCKER_COMPOSE_VERSION_2_VALUE.equals(dockerComposeDefinitionMap.get(DOCKER_COMPOSE_VERSION_KEY));
        if (isV2) {
            dockerCompositions = convertCompose(dockerComposeDefinitionMap);
        } else {
            for(String name : names) {
                CubeContainer cubeContainer = convertContainer(asMap(dockerComposeDefinitionMap, name));
                if (cubeContainer.getContainerName() != null) {
                    dockerCompositions.add(cubeContainer.getContainerName(), cubeContainer);
                } else {
                    dockerCompositions.add(name, cubeContainer);
                }
            }
        }
        return dockerCompositions;
    }`
