### ISSUE TITLE
Error : Network has active end points

### ISSUE THREAD

**Issue by RajAsapu** [arquillian/arquillian-cube#754]
I created below issue in docker java but no one commented on this. Is this something you guys can resolve ?

https://github.com/docker-java/docker-java/issues/871

**Comment by lordofthejars** [comment]
Well the error message comes from Docker Host, I will suggest to see why docker sending this message.

**Comment by RajAsapu** [comment]
@lordofthejars : I am not sure of that , but i am using arquillian + docker-compose and as the arquillian is unable to remove the network it throws an error which fails my tests because of post run tasks. Is this some thing you could handle from arquillian ? please take a look at the issue for the stack trace and other details.

**Comment by lordofthejars** [comment]
We will take a look when we have time, but the errors comes from Docker
host for sure, maybe because something wrong in Arquillian Cube (although
we have a lot of tests about networking)

El dt., 11 de jul. 2017 a les 20:16, R@j $ekh@r (<notifications@github.com>)
va escriure:

**Comment by lordofthejars** [comment]
@dipak-pawar when you have 5 minutes can you take a look at this? 

@RajAsapu can you manually delete any network created previously and try it again?

**Comment by RajAsapu** [comment]
@lordofthejars  I am able to delete the network connections manually after couple of retries and i am able to run the tests. I am assuming if at all we have a loop to check whether the network is deleted at teardown process and retry it for some x number of times it should help . I might be wrong.

**Comment by lordofthejars** [comment]
Now it works all the time? What I suspect is that network was started
manually before or jvm crashed during tests and network was there

**Comment by RajAsapu** [comment]
@lordofthejars : No , it doesn't .Below is the sequence of it

-  Run test runner (Arquillian + cucumber)
-  Creates docker containers assigns ip addresses defined in the network.
-  Runs the tests
-  Shutsdown all the containers
-  Fails while removing the custom network
-  I am able to rerun the tests after manually removing the network after trying couple of times.
-  But when i rerun again it ends up in the same issue.

**Comment by dipak-pawar** [comment]
@RajAsapu By looking into following docker-compose.yml & stacktrace looks like cube is trying to remove `price_network` which is not present in docker-compose.yml. I am wondering why cube is trying to remove `price_network` as a part of test life cycle. Is it configured somewhere?

```yaml
`version: '2'

services:
  service:
     image: 'myserviceimage'
     environment:
        - database=172.0.0.2
     ports:
        - 8080:8080
     restart: always
     networks:
          myneytwork:
            ipv4_address: 172.0.0.3
networks:
     myneytwork:
        driver: bridge
        ipam:
          config:
            - subnet: 172.0.0.0/16
              gateway: 172.0.0.1`
```
