### ISSUE TITLE
Add support for network aliases

### ISSUE THREAD

**Issue by georgwolf** [arquillian/arquillian-cube#793]
##### Issue Overview
Cube Docker is lacking support for configuring network scoped aliases (https://docs.docker.com/compose/compose-file/#aliases)

##### Expected Behaviour
Support Compose syntax for defining network aliases:

```
services:
  some-service:
    networks:
      some-network:
        aliases:
         - alias1
         - alias3
```
