### ISSUE TITLE
[Cube-Docker] DependsOn not compatible with Star Operator

### ISSUE THREAD

**Issue by georgwolf** [arquillian/arquillian-cube#845]
##### Issue Overview
depends_on is not honoured when using the star operator.
Example container definition:
```
tomcat*:
  image: tutum/tomcat:8.0
  portBindings: [8080/tcp]
  depends_on:
	- "ping*"
ping*:
  image: jonmorehouse/ping-pong
  exposedPorts: [8089/tcp]
```

##### Expected Behaviour
tomcat container is started after ping container

##### Current Behaviour
both are started in parallel
