### ISSUE TITLE
Missing support for different format of resource definition kubernetes files.

### ISSUE THREAD

**Issue by hemanik** [arquillian/arquillian-cube#852]
##### Issue Overview
Arquillian Kube does not support different formats of the resource definition yaml file. 
For instance the following file format for multiple resource definition in a single file is acceptable for kubernetes deployment but is not recognised by arquillian extension.

```
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  labels:
    app: redis
    tier: backend
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis
    tier: backend
    role: master
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-master
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        role: master
        tier: backend
    spec:
      containers:
      - name: master
        image: gcr.io/google_containers/redis:e2e  # or just image: redis
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 6379
---
```
Arquillian Kube extension supports such files with multiple resource definitions only when given as a list as below:

```
apiVersion: v1
kind: List
items:
  -
    apiVersion: v1
    kind: Service
    metadata:
      name: redis-master
      labels:
        app: redis
        tier: backend
        role: master
    spec:
      ports:
      - port: 6379
        targetPort: 6379
      selector:
        app: redis
        tier: backend
        role: master
  -
    apiVersion: extensions/v1beta1
    kind: Deployment
    metadata:
      name: redis-master
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: redis
            role: master
            tier: backend
        spec:
          containers:
          - name: master
            image: gcr.io/google_containers/redis:e2e  # or just image: redis
            ports:
            - containerPort: 6379
```
##### Expected Behaviour
All file formats acceptable by Kubernetes should ideally be supported and if not at least documented somewhere.

##### Current Behaviour
As mentioned above only the 2nd format where the multiple resource definitions are defined as a list is supported.
