### ISSUE TITLE
TemplateProcessor - IndexOutOfBoundsException

### ISSUE THREAD

**Issue by dcdh** [arquillian/arquillian-cube#998]
##### Issue Overview

I am unable to execute test using Arquillian, OpenShift with a particular setup.

When executing my tests I obtain this exception

> java.lang.IndexOutOfBoundsException: Source does not fit in dest

##### Expected Behaviour

Arquillian should setup to OpenShift a test environment and run my tests.

##### Current Behaviour

Fails with

> java.lang.IndexOutOfBoundsException: Source does not fit in dest

##### Steps To Reproduce
1. Have **syncInstantiation** defined to **true**

```
@Category(RequiresOpenshift.class)
@RequiresOpenshift
@RunWith(ArquillianConditionalRunner.class)
@Templates(templates = {@Template(url = "classpath:helloworld.yaml")}, syncInstantiation = true)
public class HelloWorldIT {
        @Test
	public void testServiceInvocation() {
        }
}
```

2. Use this **helloworld.yaml**

```
apiVersion: v1
kind: Template
metadata:
  name: hello
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: helloworld-app
  spec:
    template:
      metadata:
        labels:
          name: helloworld-service2
      spec:
        containers:
        - image: openshift/hello-openshift
          imagePullPolicy: IfNotPresent
          name: helloworld-app
```
##### Additional Information

The code throwing the exception is located on the class **openshift/openshift/src/main/java/org/arquillian/cube/openshift/impl/resources/TemplateProcessor.java**

and concerns this method:

```
    public List<? super OpenShiftResource> processTemplateResources() {
        List<? extends OpenShiftResource> resources;
        final List<? super OpenShiftResource> processedResources = new ArrayList<>();
        templates = OpenShiftResourceFactory.getTemplates(getType());
        boolean sync_instantiation = OpenShiftResourceFactory.syncInstantiation(getType());

        /* Instantiate templates */
        for (Template template : templates) {
            resources = processTemplate(template);
            if (resources != null) {
                if (sync_instantiation) {
                /* synchronous template instantiation */
                    Collections.copy(processedResources, resources);
                } else {
                /* asynchronous template instantiation */
                    try {
                        delay(openShiftAdapter, resources);
                    } catch (Throwable t) {
                        throw new IllegalArgumentException(asynchronousDelayErrorMessage(), t);
                    }
                }
            }
        }

        return processedResources;
    }
```
It failed at this line:

`Collections.copy(processedResources, resources);`

because processedResources is empty and resources contains a list of the unique DeploymentConfig so Collections.copy throw an IndexOutOfBoundsException.

I guess you should replace this code by _processedResources.addAll(resources)_

##### Workaround

Set **syncInstantiation** defined to **false**

Regards, Damien
